# generated by datamodel-codegen:
#   filename:  json_schema
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from .common import UnpinMessage


class AdminDelete(UnpinMessage):
    pass
