# generated by datamodel-codegen:
#   filename:  attachment-data.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel


class AttachmentData(BaseModel):
    data: str | None = None
