# generated by datamodel-codegen:
#   filename:  attachment-data.schema.json

from __future__ import annotations

from pydantic import BaseModel


class AttachmentData(BaseModel):
    data: str | None = None
