# generated by datamodel-codegen:
#   filename:  call-message.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class AnswerMessage(BaseModel):
    id: int
    opaque: str | None = None


class BusyMessage(BaseModel):
    id: int


class HangupMessage(BaseModel):
    device_id: int = Field(..., alias="deviceId")
    id: int
    type: str | None = None


class IceUpdateMessage(BaseModel):
    id: int
    opaque: str | None = None


class OfferMessage(BaseModel):
    id: int
    opaque: str | None = None
    type: str | None = None


class CallMessage(BaseModel):
    answer_message: AnswerMessage | None = Field(
        None, alias="answerMessage", title="JsonCallMessage.Answer"
    )
    busy_message: BusyMessage | None = Field(
        None, alias="busyMessage", title="JsonCallMessage.Busy"
    )
    hangup_message: HangupMessage | None = Field(
        None, alias="hangupMessage", title="JsonCallMessage.Hangup"
    )
    ice_update_messages: list[IceUpdateMessage] | None = Field(
        None, alias="iceUpdateMessages"
    )
    offer_message: OfferMessage | None = Field(
        None, alias="offerMessage", title="JsonCallMessage.Offer"
    )
