# generated by datamodel-codegen:
#   filename:  common.py
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import preview_schema


class BackgroundGradient(BaseModel):
    angle: int | None = None
    colors: list[str] | None = None
    end_color: str | None = Field(None, alias="endColor")
    positions: list[float] | None = None
    start_color: str | None = Field(None, alias="startColor")


class TextAttachment(BaseModel):
    background_color: str | None = Field(None, alias="backgroundColor")
    background_gradient: BackgroundGradient | None = Field(
        None,
        alias="backgroundGradient",
        title="JsonStoryMessage.TextAttachment.Gradient",
    )
    preview: preview_schema.Preview | None = None
    style: str | None = None
    text: str | None = None
    text_background_color: str | None = Field(None, alias="textBackgroundColor")
    text_foreground_color: str | None = Field(None, alias="textForegroundColor")


class ContactPhone(BaseModel):
    label: str | None = None
    type: str | None = None
    value: str | None = None


class AnswerMessage(BaseModel):
    id: int
    opaque: str | None = None


class UnpinMessage(BaseModel):
    target_author: str | None = Field(None, alias="targetAuthor")
    target_author_number: str | None = Field(None, alias="targetAuthorNumber")
    target_author_uuid: str | None = Field(None, alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
