# generated by datamodel-codegen:
#   filename:  contact-avatar.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment_schema


class ContactAvatar(BaseModel):
    attachment: attachment_schema.Attachment | None = None
    is_profile: bool = Field(..., alias="isProfile")
