# generated by datamodel-codegen:
#   filename:  contact-avatar.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment_schema import Attachment


class ContactAvatar(BaseModel):
    attachment: Attachment | None = None
    is_profile: bool = Field(..., alias="isProfile")
