# generated by datamodel-codegen:
#   filename:  data-message.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import (
        admin_delete_schema,
        attachment_schema,
        common,
        group_info_schema,
        mention_schema,
        payment_schema,
        pin_message_schema,
        poll_create_schema,
        poll_terminate_schema,
        poll_vote_schema,
        preview_schema,
        quote_schema,
        reaction_schema,
        remote_delete_schema,
        shared_contact_schema,
        sticker_schema,
        story_context_schema,
        text_style_schema,
    )


class DataMessage(BaseModel):
    admin_delete: admin_delete_schema.AdminDelete | None = Field(
        None, alias="adminDelete"
    )
    attachments: list[attachment_schema.Attachment] | None = None
    contacts: list[shared_contact_schema.SharedContact] | None = None
    expires_in_seconds: int | None = Field(None, alias="expiresInSeconds")
    group_info: group_info_schema.GroupInfo | None = Field(None, alias="groupInfo")
    is_expiration_update: bool | None = Field(None, alias="isExpirationUpdate")
    mentions: list[mention_schema.Mention] | None = None
    message: str | None = None
    payment: payment_schema.Payment | None = None
    pin_message: pin_message_schema.PinMessage | None = Field(None, alias="pinMessage")
    poll_create: poll_create_schema.PollCreate | None = Field(None, alias="pollCreate")
    poll_terminate: poll_terminate_schema.PollTerminate | None = Field(
        None, alias="pollTerminate"
    )
    poll_vote: poll_vote_schema.PollVote | None = Field(None, alias="pollVote")
    previews: list[preview_schema.Preview] | None = None
    quote: quote_schema.Quote | None = None
    reaction: reaction_schema.Reaction | None = None
    remote_delete: remote_delete_schema.RemoteDelete | None = Field(
        None, alias="remoteDelete"
    )
    sticker: sticker_schema.Sticker | None = None
    story_context: story_context_schema.StoryContext | None = Field(
        None, alias="storyContext"
    )
    text_styles: list[text_style_schema.TextStyle] | None = Field(
        None, alias="textStyles"
    )
    timestamp: int
    unpin_message: common.UnpinMessage | None = Field(None, alias="unpinMessage")
    view_once: bool | None = Field(None, alias="viewOnce")
