# generated by datamodel-codegen:
#   filename:  edit-message.schema.json

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from .data_message_schema import DataMessage


class EditMessage(BaseModel):
    data_message: DataMessage | None = Field(None, alias="dataMessage")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
