# generated by datamodel-codegen:
#   filename:  error.schema.json

from __future__ import annotations

from pydantic import BaseModel


class Error(BaseModel):
    message: str | None = None
    type: str | None = None
