# generated by datamodel-codegen:
#   filename:  internal.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Internal(BaseModel):
    capabilities: list[str] | None = None
    discoverable_by_phonenumber: bool | None = Field(
        None, alias="discoverableByPhonenumber"
    )
    shares_phone_number: bool | None = Field(None, alias="sharesPhoneNumber")
    unidentified_access_mode: str | None = Field(None, alias="unidentifiedAccessMode")
