# generated by datamodel-codegen:
#   filename:  mention.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel


class Mention(BaseModel):
    length: int
    name: str | None = None
    number: str | None = None
    start: int
    uuid: str | None = None
