# generated by datamodel-codegen:
#   filename:  message-envelope.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import (
        call_message_schema,
        data_message_schema,
        edit_message_schema,
        receipt_message_schema,
        story_message_schema,
        sync_message_schema,
        typing_message_schema,
    )


class MessageEnvelope(BaseModel):
    call_message: call_message_schema.CallMessage | None = Field(
        None, alias="callMessage"
    )
    data_message: data_message_schema.DataMessage | None = Field(
        None, alias="dataMessage"
    )
    edit_message: edit_message_schema.EditMessage | None = Field(
        None, alias="editMessage"
    )
    receipt_message: receipt_message_schema.ReceiptMessage | None = Field(
        None, alias="receiptMessage"
    )
    server_delivered_timestamp: int = Field(..., alias="serverDeliveredTimestamp")
    server_received_timestamp: int = Field(..., alias="serverReceivedTimestamp")
    source: str | None = None
    source_device: int | None = Field(None, alias="sourceDevice")
    source_name: str | None = Field(None, alias="sourceName")
    source_number: str | None = Field(None, alias="sourceNumber")
    source_uuid: str | None = Field(None, alias="sourceUuid")
    story_message: story_message_schema.StoryMessage | None = Field(
        None, alias="storyMessage"
    )
    sync_message: sync_message_schema.SyncMessage | None = Field(
        None, alias="syncMessage"
    )
    timestamp: int
    typing_message: typing_message_schema.TypingMessage | None = Field(
        None, alias="typingMessage"
    )
