# generated by datamodel-codegen:
#   filename:  message-envelope.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .call_message_schema import CallMessage
from .data_message_schema import DataMessage
from .edit_message_schema import EditMessage
from .receipt_message_schema import ReceiptMessage
from .story_message_schema import StoryMessage
from .sync_message_schema import SyncMessage
from .typing_message_schema import TypingMessage


class MessageEnvelope(BaseModel):
    call_message: CallMessage | None = Field(None, alias="callMessage")
    data_message: DataMessage | None = Field(None, alias="dataMessage")
    edit_message: EditMessage | None = Field(None, alias="editMessage")
    receipt_message: ReceiptMessage | None = Field(None, alias="receiptMessage")
    server_delivered_timestamp: int = Field(..., alias="serverDeliveredTimestamp")
    server_received_timestamp: int = Field(..., alias="serverReceivedTimestamp")
    source: str | None = None
    source_device: int | None = Field(None, alias="sourceDevice")
    source_name: str | None = Field(None, alias="sourceName")
    source_number: str | None = Field(None, alias="sourceNumber")
    source_uuid: str | None = Field(None, alias="sourceUuid")
    story_message: StoryMessage | None = Field(None, alias="storyMessage")
    sync_message: SyncMessage | None = Field(None, alias="syncMessage")
    timestamp: int
    typing_message: TypingMessage | None = Field(None, alias="typingMessage")
