# generated by datamodel-codegen:
#   filename:  payment.schema.json

from __future__ import annotations

from pydantic import BaseModel


class Payment(BaseModel):
    note: str | None = None
    receipt: str
