# generated by datamodel-codegen:
#   filename:  poll-terminate.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PollTerminate(BaseModel):
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
