# generated by datamodel-codegen:
#   filename:  preview.schema.json

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from .attachment_schema import Attachment


class Preview(BaseModel):
    description: str | None = None
    image: Attachment | None = None
    title: str | None = None
    url: str | None = None
