# generated by datamodel-codegen:
#   filename:  preview.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from . import attachment_schema


class Preview(BaseModel):
    description: str | None = None
    image: attachment_schema.Attachment | None = None
    title: str | None = None
    url: str | None = None
