# generated by datamodel-codegen:
#   filename:  profile.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Profile(BaseModel):
    about: str | None = None
    about_emoji: str | None = Field(None, alias="aboutEmoji")
    family_name: str | None = Field(None, alias="familyName")
    given_name: str | None = Field(None, alias="givenName")
    has_avatar: bool = Field(..., alias="hasAvatar")
    last_update_timestamp: int = Field(..., alias="lastUpdateTimestamp")
    mobile_coin_address: str | None = Field(None, alias="mobileCoinAddress")
