# generated by datamodel-codegen:
#   filename:  quote.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import mention_schema, quoted_attachment_schema, text_style_schema


class Quote(BaseModel):
    attachments: list[quoted_attachment_schema.QuotedAttachment] | None = None
    author: str | None = None
    author_number: str | None = Field(None, alias="authorNumber")
    author_uuid: str | None = Field(None, alias="authorUuid")
    id: int
    mentions: list[mention_schema.Mention] | None = None
    text: str | None = None
    text_styles: list[text_style_schema.TextStyle] | None = Field(
        None, alias="textStyles"
    )
