# generated by datamodel-codegen:
#   filename:  quoted-attachment.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment_schema


class QuotedAttachment(BaseModel):
    content_type: str | None = Field(None, alias="contentType")
    filename: str | None = None
    thumbnail: attachment_schema.Attachment | None = None
