# generated by datamodel-codegen:
#   filename:  quoted-attachment.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment_schema import Attachment


class QuotedAttachment(BaseModel):
    content_type: str | None = Field(None, alias="contentType")
    filename: str | None = None
    thumbnail: Attachment | None = None
