# generated by datamodel-codegen:
#   filename:  quote.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .mention_schema import Mention
from .quoted_attachment_schema import QuotedAttachment
from .text_style_schema import TextStyle


class Quote(BaseModel):
    attachments: list[QuotedAttachment] | None = None
    author: str | None = None
    author_number: str | None = Field(None, alias="authorNumber")
    author_uuid: str | None = Field(None, alias="authorUuid")
    id: int
    mentions: list[Mention] | None = None
    text: str | None = None
    text_styles: list[TextStyle] | None = Field(None, alias="textStyles")
