# generated by datamodel-codegen:
#   filename:  recipient-address.schema.json

from __future__ import annotations

from pydantic import BaseModel


class RecipientAddress(BaseModel):
    number: str | None = None
    username: str | None = None
    uuid: str | None = None
