# generated by datamodel-codegen:
#   filename:  shared-contact.schema.json

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from .common import ContactPhone
    from .contact_address_schema import ContactAddress
    from .contact_avatar_schema import ContactAvatar
    from .contact_email_schema import ContactEmail
    from .contact_name_schema import ContactName


class SharedContact(BaseModel):
    address: list[ContactAddress] | None = None
    avatar: ContactAvatar | None = None
    email: list[ContactEmail] | None = None
    name: ContactName | None = None
    organization: str | None = None
    phone: list[ContactPhone] | None = None
