# generated by datamodel-codegen:
#   filename:  sticker.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Sticker(BaseModel):
    pack_id: str | None = Field(None, alias="packId")
    sticker_id: int = Field(..., alias="stickerId")
