# generated by datamodel-codegen:
#   filename:  sticker.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Sticker(BaseModel):
    pack_id: str | None = Field(None, alias="packId")
    sticker_id: int = Field(..., alias="stickerId")
