# generated by datamodel-codegen:
#   filename:  json_schema
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

from .common import BackgroundGradient as BackgroundGradient_1
from .common import TextAttachment as TextAttachment_1

if TYPE_CHECKING:
    from . import attachment_schema


class BackgroundGradient(BackgroundGradient_1):
    pass


class TextAttachment(TextAttachment_1):
    pass


class StoryMessage(BaseModel):
    allows_replies: bool = Field(..., alias="allowsReplies")
    file_attachment: attachment_schema.Attachment | None = Field(
        None, alias="fileAttachment"
    )
    group_id: str | None = Field(None, alias="groupId")
    text_attachment: TextAttachment | None = Field(
        None, alias="textAttachment", title="JsonStoryMessage.TextAttachment"
    )
