# generated by datamodel-codegen:
#   filename:  story-context.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class StoryContext(BaseModel):
    author_number: str | None = Field(None, alias="authorNumber")
    author_uuid: str | None = Field(None, alias="authorUuid")
    sent_timestamp: int = Field(..., alias="sentTimestamp")
