# generated by datamodel-codegen:
#   filename:  sync-message.schema.json

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from .sync_data_message_schema import SyncDataMessage
    from .sync_read_message_schema import SyncReadMessage
    from .sync_story_message_schema import SyncStoryMessage


class Type(Enum):
    contacts_sync = "CONTACTS_SYNC"
    groups_sync = "GROUPS_SYNC"
    request_sync = "REQUEST_SYNC"


class SyncMessage(BaseModel):
    blocked_group_ids: list[str] | None = Field(None, alias="blockedGroupIds")
    blocked_numbers: list[str] | None = Field(None, alias="blockedNumbers")
    read_messages: list[SyncReadMessage] | None = Field(None, alias="readMessages")
    sent_message: SyncDataMessage | None = Field(None, alias="sentMessage")
    sent_story_message: SyncStoryMessage | None = Field(None, alias="sentStoryMessage")
    type: Type | None = None
