# generated by datamodel-codegen:
#   filename:  sync-story-message.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment_schema, common


class SyncStoryMessage(BaseModel):
    destination_number: str = Field(..., alias="destinationNumber")
    destination_uuid: str = Field(..., alias="destinationUuid")
    allows_replies: bool = Field(..., alias="allowsReplies")
    file_attachment: attachment_schema.Attachment | None = Field(
        None, alias="fileAttachment"
    )
    group_id: str | None = Field(None, alias="groupId")
    text_attachment: common.TextAttachment | None = Field(
        None, alias="textAttachment", title="JsonStoryMessage.TextAttachment"
    )
