# generated by datamodel-codegen:
#   filename:  sync-story-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment_schema import Attachment
from .shared import TextAttachment


class SyncStoryMessage(BaseModel):
    destination_number: str = Field(..., alias="destinationNumber")
    destination_uuid: str = Field(..., alias="destinationUuid")
    allows_replies: bool = Field(..., alias="allowsReplies")
    file_attachment: Attachment | None = Field(None, alias="fileAttachment")
    group_id: str | None = Field(None, alias="groupId")
    text_attachment: TextAttachment | None = Field(
        None, alias="textAttachment", title="JsonStoryMessage.TextAttachment"
    )
