# generated by datamodel-codegen:
#   filename:  text-style.schema.json
#   timestamp: 2026-03-07T23:22:36+00:00

from __future__ import annotations

from pydantic import BaseModel


class TextStyle(BaseModel):
    length: int
    start: int
    style: str | None = None
