# generated by datamodel-codegen:
#   filename:  text-style.schema.json

from __future__ import annotations

from pydantic import BaseModel


class TextStyle(BaseModel):
    length: int
    start: int
    style: str | None = None
