# generated by datamodel-codegen:
#   filename:  typing-message.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TypingMessage(BaseModel):
    action: str | None = None
    group_id: str | None = Field(None, alias="groupId")
    timestamp: int
