# generated by datamodel-codegen:
#   filename:  typing-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class TypingMessage(BaseModel):
    action: str | None = None
    group_id: str | None = Field(default=None, alias="groupId")
    timestamp: int
