# generated by datamodel-codegen:
#   filename:  admin-delete.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class AdminDelete(BaseModel):
    target_author: str | None = Field(None, alias="targetAuthor")
    target_author_number: str | None = Field(None, alias="targetAuthorNumber")
    target_author_uuid: str | None = Field(None, alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
