# generated by datamodel-codegen:
#   filename:  story-message.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment_schema, preview_schema


class BackgroundGradient(BaseModel):
    angle: int | None = None
    colors: list[str] | None = None
    end_color: str | None = Field(None, alias="endColor")
    positions: list[float] | None = None
    start_color: str | None = Field(None, alias="startColor")


class TextAttachment(BaseModel):
    background_color: str | None = Field(None, alias="backgroundColor")
    background_gradient: BackgroundGradient | None = Field(
        None,
        alias="backgroundGradient",
        title="JsonStoryMessage.TextAttachment.Gradient",
    )
    preview: preview_schema.Preview | None = None
    style: str | None = None
    text: str | None = None
    text_background_color: str | None = Field(None, alias="textBackgroundColor")
    text_foreground_color: str | None = Field(None, alias="textForegroundColor")


class StoryMessage(BaseModel):
    allows_replies: bool = Field(..., alias="allowsReplies")
    file_attachment: attachment_schema.Attachment | None = Field(
        None, alias="fileAttachment"
    )
    group_id: str | None = Field(None, alias="groupId")
    text_attachment: TextAttachment | None = Field(
        None, alias="textAttachment", title="JsonStoryMessage.TextAttachment"
    )
