# generated by datamodel-codegen:
#   filename:  contact-phone.schema.json

from __future__ import annotations

from pydantic import BaseModel


class ContactPhone(BaseModel):
    label: str | None = None
    type: str | None = None
    value: str | None = None
