# generated by datamodel-codegen:
#   filename:  mention.schema.json

from __future__ import annotations

from pydantic import BaseModel


class Mention(BaseModel):
    length: int
    name: str | None = None
    number: str | None = None
    start: int
    uuid: str | None = None
