# generated by datamodel-codegen:
#   filename:  json_schema

from __future__ import annotations

from pydantic import BaseModel, Field

from .attachment_schema import Attachment
from .shared import BackgroundGradient as BackgroundGradient_1
from .shared import TextAttachment as TextAttachment_1


class BackgroundGradient(BackgroundGradient_1):
    pass


class TextAttachment(TextAttachment_1):
    pass


class StoryMessage(BaseModel):
    allows_replies: bool = Field(..., alias="allowsReplies")
    file_attachment: Attachment | None = Field(None, alias="fileAttachment")
    group_id: str | None = Field(None, alias="groupId")
    text_attachment: TextAttachment | None = Field(
        None, alias="textAttachment", title="JsonStoryMessage.TextAttachment"
    )
