# generated by datamodel-codegen:
#   filename:  json_schema_receive

from __future__ import annotations

from .admin_delete_schema import AdminDelete
from .attachment_data_schema import AttachmentData
from .attachment_schema import Attachment
from .call_message_schema import (
    AnswerMessage,
    BusyMessage,
    CallMessage,
    HangupMessage,
    IceUpdateMessage,
    OfferMessage,
)
from .contact_address_schema import ContactAddress
from .contact_avatar_schema import ContactAvatar
from .contact_email_schema import ContactEmail
from .contact_name_schema import ContactName
from .contact_phone_schema import ContactPhone
from .contact_schema import Contact
from .data_message_schema import DataMessage
from .edit_message_schema import EditMessage
from .error_schema import Error
from .group_info_schema import GroupInfo
from .internal_schema import Internal
from .mention_schema import Mention
from .message_envelope_schema import MessageEnvelope
from .payment_schema import Payment
from .pin_message_schema import PinMessage
from .poll_create_schema import PollCreate
from .poll_terminate_schema import PollTerminate
from .poll_vote_schema import PollVote
from .preview_schema import Preview
from .profile_schema import Profile
from .quote_schema import Quote
from .quoted_attachment_schema import QuotedAttachment
from .reaction_schema import Reaction
from .receipt_message_schema import ReceiptMessage
from .recipient_address_schema import RecipientAddress
from .remote_delete_schema import RemoteDelete
from .send_message_result_schema import SendMessageResult
from .send_message_result_schema import Type as SendMessageResultSchemaType
from .shared_contact_schema import SharedContact
from .sticker_schema import Sticker
from .story_context_schema import StoryContext
from .story_message_schema import (
    BackgroundGradient as StoryMessageSchemaBackgroundGradient,
)
from .story_message_schema import StoryMessage
from .story_message_schema import TextAttachment as StoryMessageSchemaTextAttachment
from .sync_data_message_schema import SyncDataMessage
from .sync_message_schema import SyncMessage
from .sync_message_schema import Type as SyncMessageSchemaType
from .sync_read_message_schema import SyncReadMessage
from .sync_story_message_schema import (
    BackgroundGradient as SyncStoryMessageSchemaBackgroundGradient,
)
from .sync_story_message_schema import SyncStoryMessage
from .sync_story_message_schema import (
    TextAttachment as SyncStoryMessageSchemaTextAttachment,
)
from .text_style_schema import TextStyle
from .typing_message_schema import TypingMessage
from .unpin_message_schema import UnpinMessage

__all__ = [
    "AdminDelete",
    "AnswerMessage",
    "Attachment",
    "AttachmentData",
    "BusyMessage",
    "CallMessage",
    "Contact",
    "ContactAddress",
    "ContactAvatar",
    "ContactEmail",
    "ContactName",
    "ContactPhone",
    "DataMessage",
    "EditMessage",
    "Error",
    "GroupInfo",
    "HangupMessage",
    "IceUpdateMessage",
    "Internal",
    "Mention",
    "MessageEnvelope",
    "OfferMessage",
    "Payment",
    "PinMessage",
    "PollCreate",
    "PollTerminate",
    "PollVote",
    "Preview",
    "Profile",
    "Quote",
    "QuotedAttachment",
    "Reaction",
    "ReceiptMessage",
    "RecipientAddress",
    "RemoteDelete",
    "SendMessageResult",
    "SendMessageResultSchemaType",
    "SharedContact",
    "Sticker",
    "StoryContext",
    "StoryMessage",
    "StoryMessageSchemaBackgroundGradient",
    "StoryMessageSchemaTextAttachment",
    "SyncDataMessage",
    "SyncMessage",
    "SyncMessageSchemaType",
    "SyncReadMessage",
    "SyncStoryMessage",
    "SyncStoryMessageSchemaBackgroundGradient",
    "SyncStoryMessageSchemaTextAttachment",
    "TextStyle",
    "TypingMessage",
    "UnpinMessage",
]
