# generated by datamodel-codegen:
#   filename:  contact-email.schema.json

from __future__ import annotations

from pydantic import BaseModel


class ContactEmail(BaseModel):
    label: str | None = None
    type: str | None = None
    value: str | None = None
