# generated by datamodel-codegen:
#   filename:  edit-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .data_message_schema import DataMessage


class EditMessage(BaseModel):
    data_message: DataMessage | None = Field(default=None, alias="dataMessage")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
