# generated by datamodel-codegen:
#   filename:  group-info.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class GroupInfo(BaseModel):
    group_id: str | None = Field(default=None, alias="groupId")
    group_name: str | None = Field(default=None, alias="groupName")
    revision: int
    type: str | None = None
