# generated by datamodel-codegen:
#   filename:  internal.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class Internal(BaseModel):
    capabilities: list[str] | None = None
    discoverable_by_phonenumber: bool | None = Field(
        None, alias="discoverableByPhonenumber"
    )
    shares_phone_number: bool | None = Field(default=None, alias="sharesPhoneNumber")
    unidentified_access_mode: str | None = Field(
        default=None, alias="unidentifiedAccessMode"
    )
