# generated by datamodel-codegen:
#   filename:  pin-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class PinMessage(BaseModel):
    pin_duration_seconds: int = Field(..., alias="pinDurationSeconds")
    target_author: str | None = Field(default=None, alias="targetAuthor")
    target_author_number: str | None = Field(default=None, alias="targetAuthorNumber")
    target_author_uuid: str | None = Field(default=None, alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
