# generated by datamodel-codegen:
#   filename:  poll-terminate.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class PollTerminate(BaseModel):
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
