# generated by datamodel-codegen:
#   filename:  receipt-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class ReceiptMessage(BaseModel):
    is_delivery: bool = Field(..., alias="isDelivery")
    is_read: bool = Field(..., alias="isRead")
    is_viewed: bool = Field(..., alias="isViewed")
    timestamps: list[int] | None = None
    when: int
