# generated by datamodel-codegen:
#   filename:  story-context.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class StoryContext(BaseModel):
    author_number: str | None = Field(default=None, alias="authorNumber")
    author_uuid: str | None = Field(default=None, alias="authorUuid")
    sent_timestamp: int = Field(..., alias="sentTimestamp")
