# generated by datamodel-codegen:
#   filename:  sync-read-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field


class SyncReadMessage(BaseModel):
    sender: str | None = None
    sender_number: str | None = Field(default=None, alias="senderNumber")
    sender_uuid: str | None = Field(default=None, alias="senderUuid")
    timestamp: int
