# generated by datamodel-codegen:
#   filename:  sync-data-message.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from .admin_delete_schema import AdminDelete
from .attachment_schema import Attachment
from .edit_message_schema import EditMessage
from .group_info_schema import GroupInfo
from .mention_schema import Mention
from .payment_schema import Payment
from .pin_message_schema import PinMessage
from .poll_create_schema import PollCreate
from .poll_terminate_schema import PollTerminate
from .poll_vote_schema import PollVote
from .preview_schema import Preview
from .quote_schema import Quote
from .reaction_schema import Reaction
from .remote_delete_schema import RemoteDelete
from .shared_contact_schema import SharedContact
from .sticker_schema import Sticker
from .story_context_schema import StoryContext
from .text_style_schema import TextStyle
from .unpin_message_schema import UnpinMessage


class SyncDataMessage(BaseModel):
    admin_delete: AdminDelete | None = Field(None, alias="adminDelete")
    attachments: list[Attachment] | None = None
    contacts: list[SharedContact] | None = None
    destination: str | None = None
    destination_number: str | None = Field(None, alias="destinationNumber")
    destination_uuid: str | None = Field(None, alias="destinationUuid")
    edit_message: EditMessage | None = Field(None, alias="editMessage")
    expires_in_seconds: int | None = Field(None, alias="expiresInSeconds")
    group_info: GroupInfo | None = Field(None, alias="groupInfo")
    is_expiration_update: bool | None = Field(None, alias="isExpirationUpdate")
    mentions: list[Mention] | None = None
    message: str | None = None
    payment: Payment | None = None
    pin_message: PinMessage | None = Field(None, alias="pinMessage")
    poll_create: PollCreate | None = Field(None, alias="pollCreate")
    poll_terminate: PollTerminate | None = Field(None, alias="pollTerminate")
    poll_vote: PollVote | None = Field(None, alias="pollVote")
    previews: list[Preview] | None = None
    quote: Quote | None = None
    reaction: Reaction | None = None
    remote_delete: RemoteDelete | None = Field(None, alias="remoteDelete")
    sticker: Sticker | None = None
    story_context: StoryContext | None = Field(None, alias="storyContext")
    text_styles: list[TextStyle] | None = Field(None, alias="textStyles")
    timestamp: int | None = None
    unpin_message: UnpinMessage | None = Field(None, alias="unpinMessage")
    view_once: bool | None = Field(None, alias="viewOnce")
