# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from pydantic import BaseModel

from .data import GroupPermissions


class About(BaseModel):
    build: int | None = None
    capabilities: dict[str, list[str]] | None = None
    mode: str | None = None
    version: str | None = None
    versions: list[str] | None = None


class ContactProfile(BaseModel):
    about: str | None = None
    given_name: str | None = None
    has_avatar: bool | None = None
    last_updated_timestamp: int | None = None
    lastname: str | None = None


class IdentityEntry(BaseModel):
    added: str | None = None
    fingerprint: str | None = None
    number: str | None = None
    safety_number: str | None = None
    status: str | None = None
    uuid: str | None = None


class ListDevicesResponse(BaseModel):
    creation_timestamp: int | None = None
    id: int | None = None
    last_seen_timestamp: int | None = None
    name: str | None = None


class ListInstalledStickerPacksResponse(BaseModel):
    author: str | None = None
    installed: bool | None = None
    pack_id: str | None = None
    title: str | None = None
    url: str | None = None


class Nickname(BaseModel):
    family_name: str | None = None
    given_name: str | None = None
    name: str | None = None


class SetUsernameResponse(BaseModel):
    username: str | None = None
    username_link: str | None = None


class GroupEntry(BaseModel):
    admins: list[str] | None = None
    blocked: bool | None = None
    description: str | None = None
    id: str | None = None
    internal_id: str | None = None
    invite_link: str | None = None
    members: list[str] | None = None
    name: str | None = None
    pending_invites: list[str] | None = None
    pending_requests: list[str] | None = None
    permissions: GroupPermissions | None = None


class ListContactsResponse(BaseModel):
    blocked: bool | None = None
    color: str | None = None
    given_name: str | None = None
    message_expiration: str | None = None
    name: str | None = None
    nickname: Nickname | None = None
    note: str | None = None
    number: str | None = None
    profile: ContactProfile | None = None
    profile_name: str | None = None
    username: str | None = None
    uuid: str | None = None
