# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Attachment(BaseModel):
    content_type: str = Field(..., alias="contentType")
    filename: str
    id: str
    size: int
    width: int
    height: int
    caption: str
    upload_timestamp: int = Field(..., alias="uploadTimestamp")
