# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import answer, busy, hangup, ice_update, offer


class CallMessage(BaseModel):
    offer_message: offer.Offer | None = Field(None, alias="offerMessage")
    answer_message: answer.Answer | None = Field(None, alias="answerMessage")
    busy_message: busy.Busy | None = Field(None, alias="busyMessage")
    hangup_message: hangup.Hangup | None = Field(None, alias="hangupMessage")
    ice_update_messages: list[ice_update.IceUpdate] | None = Field(
        None, alias="iceUpdateMessages"
    )
