# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel


class ContactAddress(BaseModel):
    type: str
    label: str
    street: str
    pobox: str
    neighborhood: str
    city: str
    region: str
    postcode: str
    country: str
