# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment as attachment_1


class ContactAvatar(BaseModel):
    attachment: attachment_1.Attachment
    is_profile: bool = Field(..., alias="isProfile")
