# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import internal as internal_1
    from . import profile as profile_1


class Contact(BaseModel):
    number: str
    uuid: str
    username: str
    name: str
    given_name: str = Field(..., alias="givenName")
    family_name: str = Field(..., alias="familyName")
    nick_name: str = Field(..., alias="nickName")
    nick_given_name: str = Field(..., alias="nickGivenName")
    nick_family_name: str = Field(..., alias="nickFamilyName")
    note: str
    color: str
    is_blocked: bool = Field(..., alias="isBlocked")
    is_hidden: bool = Field(..., alias="isHidden")
    message_expiration_time: int = Field(..., alias="messageExpirationTime")
    profile_sharing: bool = Field(..., alias="profileSharing")
    unregistered: bool
    profile: profile_1.Profile
    internal: internal_1.Internal | None = None
