# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import admin_delete as admin_delete_1
    from . import attachment, mention, preview, shared_contact, text_style
    from . import group_info as group_info_1
    from . import payment as payment_1
    from . import pin_message as pin_message_1
    from . import poll_create as poll_create_1
    from . import poll_terminate as poll_terminate_1
    from . import poll_vote as poll_vote_1
    from . import quote as quote_1
    from . import reaction as reaction_1
    from . import remote_delete as remote_delete_1
    from . import sticker as sticker_1
    from . import story_context as story_context_1
    from . import unpin_message as unpin_message_1


class DataMessage(BaseModel):
    timestamp: int
    message: str
    expires_in_seconds: int = Field(..., alias="expiresInSeconds")
    is_expiration_update: bool | None = Field(None, alias="isExpirationUpdate")
    view_once: bool | None = Field(None, alias="viewOnce")
    reaction: reaction_1.Reaction | None = None
    quote: quote_1.Quote | None = None
    payment: payment_1.Payment | None = None
    mentions: list[mention.Mention] | None = None
    previews: list[preview.Preview] | None = None
    attachments: list[attachment.Attachment] | None = None
    sticker: sticker_1.Sticker | None = None
    remote_delete: remote_delete_1.RemoteDelete | None = Field(
        None, alias="remoteDelete"
    )
    contacts: list[shared_contact.SharedContact] | None = None
    poll_create: poll_create_1.PollCreate | None = Field(None, alias="pollCreate")
    poll_vote: poll_vote_1.PollVote | None = Field(None, alias="pollVote")
    poll_terminate: poll_terminate_1.PollTerminate | None = Field(
        None, alias="pollTerminate"
    )
    text_styles: list[text_style.TextStyle] | None = Field(None, alias="textStyles")
    group_info: group_info_1.GroupInfo | None = Field(None, alias="groupInfo")
    story_context: story_context_1.StoryContext | None = Field(
        None, alias="storyContext"
    )
    pin_message: pin_message_1.PinMessage | None = Field(None, alias="pinMessage")
    unpin_message: unpin_message_1.UnpinMessage | None = Field(
        None, alias="unpinMessage"
    )
    admin_delete: admin_delete_1.AdminDelete | None = Field(None, alias="adminDelete")
