# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import data_message as data_message_1


class EditMessage(BaseModel):
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    data_message: data_message_1.DataMessage = Field(..., alias="dataMessage")
