# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Gradient(BaseModel):
    start_color: str = Field(..., alias="startColor")
    end_color: str = Field(..., alias="endColor")
    colors: list[str]
    positions: list[float]
    angle: int
