# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class GroupInfo(BaseModel):
    group_id: str = Field(..., alias="groupId")
    group_name: str = Field(..., alias="groupName")
    revision: int
    type: str
