# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Internal(BaseModel):
    capabilities: list[str]
    unidentified_access_mode: str = Field(..., alias="unidentifiedAccessMode")
    shares_phone_number: bool = Field(..., alias="sharesPhoneNumber")
    discoverable_by_phonenumber: bool = Field(..., alias="discoverableByPhonenumber")
