# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Mention(BaseModel):
    name: str = Field(..., deprecated=True)
    number: str
    uuid: str
    start: int
    length: int
