# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import call_message as call_message_1
    from . import data_message as data_message_1
    from . import edit_message as edit_message_1
    from . import receipt_message as receipt_message_1
    from . import story_message as story_message_1
    from . import sync_message as sync_message_1
    from . import typing_message as typing_message_1


class MessageEnvelope(BaseModel):
    source: str = Field(..., deprecated=True)
    source_number: str = Field(..., alias="sourceNumber")
    source_uuid: str = Field(..., alias="sourceUuid")
    source_name: str = Field(..., alias="sourceName")
    source_device: int = Field(..., alias="sourceDevice")
    timestamp: int
    server_received_timestamp: int = Field(..., alias="serverReceivedTimestamp")
    server_delivered_timestamp: int = Field(..., alias="serverDeliveredTimestamp")
    data_message: data_message_1.DataMessage | None = Field(None, alias="dataMessage")
    edit_message: edit_message_1.EditMessage | None = Field(None, alias="editMessage")
    story_message: story_message_1.StoryMessage | None = Field(
        None, alias="storyMessage"
    )
    sync_message: sync_message_1.SyncMessage | None = Field(None, alias="syncMessage")
    call_message: call_message_1.CallMessage | None = Field(None, alias="callMessage")
    receipt_message: receipt_message_1.ReceiptMessage | None = Field(
        None, alias="receiptMessage"
    )
    typing_message: typing_message_1.TypingMessage | None = Field(
        None, alias="typingMessage"
    )
