# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import Base64Str, BaseModel


class Payment(BaseModel):
    note: str
    receipt: Base64Str
