# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PollCreate(BaseModel):
    question: str
    allow_multiple: bool = Field(..., alias="allowMultiple")
    options: list[str]
