# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PollVote(BaseModel):
    author: str = Field(..., deprecated=True)
    author_number: str = Field(..., alias="authorNumber")
    author_uuid: str = Field(..., alias="authorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    option_indexes: list[int] = Field(..., alias="optionIndexes")
    vote_count: int = Field(..., alias="voteCount")
