# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Profile(BaseModel):
    last_update_timestamp: int = Field(..., alias="lastUpdateTimestamp")
    given_name: str = Field(..., alias="givenName")
    family_name: str = Field(..., alias="familyName")
    about: str
    about_emoji: str = Field(..., alias="aboutEmoji")
    has_avatar: bool = Field(..., alias="hasAvatar")
    mobile_coin_address: str = Field(..., alias="mobileCoinAddress")
