# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import mention, quoted_attachment, text_style


class Quote(BaseModel):
    id: int
    author: str = Field(..., deprecated=True)
    author_number: str = Field(..., alias="authorNumber")
    author_uuid: str = Field(..., alias="authorUuid")
    text: str
    mentions: list[mention.Mention] | None = None
    attachments: list[quoted_attachment.QuotedAttachment]
    text_styles: list[text_style.TextStyle] | None = Field(None, alias="textStyles")
