# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment


class QuotedAttachment(BaseModel):
    content_type: str = Field(..., alias="contentType")
    filename: str
    thumbnail: attachment.Attachment | None = None
