# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Reaction(BaseModel):
    emoji: str
    target_author: str = Field(..., alias="targetAuthor", deprecated=True)
    target_author_number: str = Field(..., alias="targetAuthorNumber")
    target_author_uuid: str = Field(..., alias="targetAuthorUuid")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    is_remove: bool = Field(..., alias="isRemove")
