# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ReceiptMessage(BaseModel):
    when: int
    is_delivery: bool = Field(..., alias="isDelivery")
    is_read: bool = Field(..., alias="isRead")
    is_viewed: bool = Field(..., alias="isViewed")
    timestamps: list[int]
