# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import admin_delete as admin_delete_1
    from . import attachment as attachment_1
    from . import attachment_data as attachment_data_1
    from . import call_message as call_message_1
    from . import contact as contact_1
    from . import contact_address as contact_address_1
    from . import contact_avatar as contact_avatar_1
    from . import contact_email as contact_email_1
    from . import contact_name as contact_name_1
    from . import contact_phone as contact_phone_1
    from . import data_message as data_message_1
    from . import edit_message as edit_message_1
    from . import error as error_1
    from . import group_info as group_info_1
    from . import mention as mention_1
    from . import message_envelope as message_envelope_1
    from . import payment as payment_1
    from . import pin_message as pin_message_1
    from . import poll_create as poll_create_1
    from . import poll_terminate as poll_terminate_1
    from . import poll_vote as poll_vote_1
    from . import preview as preview_1
    from . import quote as quote_1
    from . import quoted_attachment as quoted_attachment_1
    from . import reaction as reaction_1
    from . import receipt_message as receipt_message_1
    from . import recipient_address as recipient_address_1
    from . import remote_delete as remote_delete_1
    from . import send_message_result as send_message_result_1
    from . import shared_contact as shared_contact_1
    from . import sticker as sticker_1
    from . import story_context as story_context_1
    from . import story_message as story_message_1
    from . import sync_data_message as sync_data_message_1
    from . import sync_message as sync_message_1
    from . import sync_read_message as sync_read_message_1
    from . import sync_story_message as sync_story_message_1
    from . import text_style as text_style_1
    from . import typing_message as typing_message_1
    from . import unpin_message as unpin_message_1


class SchemaCatalog(BaseModel):
    admin_delete: admin_delete_1.AdminDelete | None = Field(None, alias="adminDelete")
    attachment: attachment_1.Attachment | None = None
    attachment_data: attachment_data_1.AttachmentData | None = Field(
        None, alias="attachmentData"
    )
    call_message: call_message_1.CallMessage | None = Field(None, alias="callMessage")
    contact: contact_1.Contact | None = None
    contact_address: contact_address_1.ContactAddress | None = Field(
        None, alias="contactAddress"
    )
    contact_avatar: contact_avatar_1.ContactAvatar | None = Field(
        None, alias="contactAvatar"
    )
    contact_email: contact_email_1.ContactEmail | None = Field(
        None, alias="contactEmail"
    )
    contact_name: contact_name_1.ContactName | None = Field(None, alias="contactName")
    contact_phone: contact_phone_1.ContactPhone | None = Field(
        None, alias="contactPhone"
    )
    data_message: data_message_1.DataMessage | None = Field(None, alias="dataMessage")
    edit_message: edit_message_1.EditMessage | None = Field(None, alias="editMessage")
    error: error_1.Error | None = None
    group_info: group_info_1.GroupInfo | None = Field(None, alias="groupInfo")
    mention: mention_1.Mention | None = None
    message_envelope: message_envelope_1.MessageEnvelope | None = Field(
        None, alias="messageEnvelope"
    )
    payment: payment_1.Payment | None = None
    pin_message: pin_message_1.PinMessage | None = Field(None, alias="pinMessage")
    poll_create: poll_create_1.PollCreate | None = Field(None, alias="pollCreate")
    poll_terminate: poll_terminate_1.PollTerminate | None = Field(
        None, alias="pollTerminate"
    )
    poll_vote: poll_vote_1.PollVote | None = Field(None, alias="pollVote")
    preview: preview_1.Preview | None = None
    quote: quote_1.Quote | None = None
    quoted_attachment: quoted_attachment_1.QuotedAttachment | None = Field(
        None, alias="quotedAttachment"
    )
    reaction: reaction_1.Reaction | None = None
    receipt_message: receipt_message_1.ReceiptMessage | None = Field(
        None, alias="receiptMessage"
    )
    recipient_address: recipient_address_1.RecipientAddress | None = Field(
        None, alias="recipientAddress"
    )
    remote_delete: remote_delete_1.RemoteDelete | None = Field(
        None, alias="remoteDelete"
    )
    send_message_result: send_message_result_1.SendMessageResult | None = Field(
        None, alias="sendMessageResult"
    )
    shared_contact: shared_contact_1.SharedContact | None = Field(
        None, alias="sharedContact"
    )
    sticker: sticker_1.Sticker | None = None
    story_context: story_context_1.StoryContext | None = Field(
        None, alias="storyContext"
    )
    story_message: story_message_1.StoryMessage | None = Field(
        None, alias="storyMessage"
    )
    sync_data_message: sync_data_message_1.SyncDataMessage | None = Field(
        None, alias="syncDataMessage"
    )
    sync_message: sync_message_1.SyncMessage | None = Field(None, alias="syncMessage")
    sync_read_message: sync_read_message_1.SyncReadMessage | None = Field(
        None, alias="syncReadMessage"
    )
    sync_story_message: sync_story_message_1.SyncStoryMessage | None = Field(
        None, alias="syncStoryMessage"
    )
    text_style: text_style_1.TextStyle | None = Field(None, alias="textStyle")
    typing_message: typing_message_1.TypingMessage | None = Field(
        None, alias="typingMessage"
    )
    unpin_message: unpin_message_1.UnpinMessage | None = Field(
        None, alias="unpinMessage"
    )
    attachments: list[attachment_1.Attachment] | None = None
    mentions: list[mention_1.Mention] | None = None
    previews: list[preview_1.Preview] | None = None
    contacts: list[shared_contact_1.SharedContact] | None = None
    text_styles: list[text_style_1.TextStyle] | None = Field(None, alias="textStyles")
