# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from . import (
        contact_address,
        contact_avatar,
        contact_email,
        contact_name,
        contact_phone,
    )


class SharedContact(BaseModel):
    name: contact_name.ContactName
    avatar: contact_avatar.ContactAvatar | None = None
    phone: list[contact_phone.ContactPhone] | None = None
    email: list[contact_email.ContactEmail] | None = None
    address: list[contact_address.ContactAddress] | None = None
    organization: str
