# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import sync_data_message, sync_read_message, sync_story_message, type1


class SyncMessage(BaseModel):
    sent_message: sync_data_message.SyncDataMessage | None = Field(
        None, alias="sentMessage"
    )
    sent_story_message: sync_story_message.SyncStoryMessage | None = Field(
        None, alias="sentStoryMessage"
    )
    blocked_numbers: list[str] | None = Field(None, alias="blockedNumbers")
    blocked_group_ids: list[str] | None = Field(None, alias="blockedGroupIds")
    read_messages: list[sync_read_message.SyncReadMessage] | None = Field(
        None, alias="readMessages"
    )
    type: type1.Type | None = None
