# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SyncReadMessage(BaseModel):
    sender: str = Field(..., deprecated=True)
    sender_number: str = Field(..., alias="senderNumber")
    sender_uuid: str = Field(..., alias="senderUuid")
    timestamp: int
