# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import attachment
    from . import text_attachment as text_attachment_1


class SyncStoryMessage(BaseModel):
    destination_number: str = Field(..., alias="destinationNumber")
    destination_uuid: str = Field(..., alias="destinationUuid")
    allows_replies: bool = Field(..., alias="allowsReplies")
    group_id: str | None = Field(None, alias="groupId")
    file_attachment: attachment.Attachment | None = Field(None, alias="fileAttachment")
    text_attachment: text_attachment_1.TextAttachment | None = Field(
        None, alias="textAttachment"
    )
    data_message: Any = Field(..., alias="dataMessage")
