# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import gradient
    from . import preview as preview_1


class TextAttachment(BaseModel):
    text: str
    style: str | None = None
    text_foreground_color: str | None = Field(None, alias="textForegroundColor")
    text_background_color: str | None = Field(None, alias="textBackgroundColor")
    preview: preview_1.Preview | None = None
    background_gradient: gradient.Gradient | None = Field(
        None, alias="backgroundGradient"
    )
    background_color: str | None = Field(None, alias="backgroundColor")
