# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from enum import Enum


class Type(Enum):
    success = "SUCCESS"
    network_failure = "NETWORK_FAILURE"
    unregistered_failure = "UNREGISTERED_FAILURE"
    identity_failure = "IDENTITY_FAILURE"
    rate_limit_failure = "RATE_LIMIT_FAILURE"
    invalid_pre_key_failure = "INVALID_PRE_KEY_FAILURE"
