# generated by datamodel-codegen:
#   filename:  json-models_swagger.json
#   timestamp: 2026-03-06T22:52:06+00:00

from __future__ import annotations

from enum import Enum


class Type(Enum):
    contacts_sync = "CONTACTS_SYNC"
    groups_sync = "GROUPS_SYNC"
    request_sync = "REQUEST_SYNC"
