# generated by datamodel-codegen:
#   filename:  attachment.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Attachment(BaseModel):
    caption: str | None = None
    content_type: str | None = Field(None, alias="contentType")
    filename: str | None = None
    height: int | None = None
    id: str | None = None
    size: int | None = None
    upload_timestamp: int | None = Field(None, alias="uploadTimestamp")
    width: int | None = None
