# generated by datamodel-codegen:
#   filename:  contact-address.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class ContactAddress(BaseModel):
    city: str | None = None
    country: str | None = None
    label: str | None = None
    neighborhood: str | None = None
    pobox: str | None = None
    postcode: str | None = None
    region: str | None = None
    street: str | None = None
    type: str | None = None
