# generated by datamodel-codegen:
#   filename:  contact-name.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class ContactName(BaseModel):
    family: str | None = None
    given: str | None = None
    middle: str | None = None
    nickname: str | None = None
    prefix: str | None = None
    suffix: str | None = None
