# generated by datamodel-codegen:
#   filename:  contact-phone.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class ContactPhone(BaseModel):
    label: str | None = None
    type: str | None = None
    value: str | None = None
