# generated by datamodel-codegen:
#   filename:  poll-create.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PollCreate(BaseModel):
    allow_multiple: bool = Field(..., alias="allowMultiple")
    options: list[str] | None = None
    question: str | None = None
