# generated by datamodel-codegen:
#   filename:  recipient-address.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class RecipientAddress(BaseModel):
    number: str | None = None
    username: str | None = None
    uuid: str | None = None
