# generated by datamodel-codegen:
#   filename:  remote-delete.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel


class RemoteDelete(BaseModel):
    timestamp: int
