# generated by datamodel-codegen:
#   filename:  sync-message.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import (
        sync_data_message_schema,
        sync_read_message_schema,
        sync_story_message_schema,
    )


class Type(Enum):
    contacts_sync = "CONTACTS_SYNC"
    groups_sync = "GROUPS_SYNC"
    request_sync = "REQUEST_SYNC"


class SyncMessage(BaseModel):
    blocked_group_ids: list[str] | None = Field(None, alias="blockedGroupIds")
    blocked_numbers: list[str] | None = Field(None, alias="blockedNumbers")
    read_messages: list[sync_read_message_schema.SyncReadMessage] | None = Field(
        None, alias="readMessages"
    )
    sent_message: sync_data_message_schema.SyncDataMessage | None = Field(
        None, alias="sentMessage"
    )
    sent_story_message: sync_story_message_schema.SyncStoryMessage | None = Field(
        None, alias="sentStoryMessage"
    )
    type: Type | None = None
