# generated by datamodel-codegen:
#   filename:  sync-read-message.schema.json
#   timestamp: 2026-03-07T01:22:53+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SyncReadMessage(BaseModel):
    sender: str | None = None
    sender_number: str | None = Field(None, alias="senderNumber")
    sender_uuid: str | None = Field(None, alias="senderUuid")
    timestamp: int
