# generated by datamodel-codegen:
#   filename:  edit-message.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from . import data_message_schema


class EditMessage(BaseModel):
    data_message: data_message_schema.DataMessage | None = Field(
        None, alias="dataMessage"
    )
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
