# generated by datamodel-codegen:
#   filename:  group-info.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class GroupInfo(BaseModel):
    group_id: str | None = Field(None, alias="groupId")
    group_name: str | None = Field(None, alias="groupName")
    revision: int
    type: str | None = None
