# generated by datamodel-codegen:
#   filename:  poll-vote.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PollVote(BaseModel):
    author: str | None = None
    author_number: str | None = Field(None, alias="authorNumber")
    author_uuid: str | None = Field(None, alias="authorUuid")
    option_indexes: list[int] | None = Field(None, alias="optionIndexes")
    target_sent_timestamp: int = Field(..., alias="targetSentTimestamp")
    vote_count: int = Field(..., alias="voteCount")
