# generated by datamodel-codegen:
#   filename:  shared-contact.schema.json
#   timestamp: 2026-03-07T20:47:26+00:00

from __future__ import annotations

from typing import TYPE_CHECKING

from pydantic import BaseModel

if TYPE_CHECKING:
    from . import (
        contact_address_schema,
        contact_avatar_schema,
        contact_email_schema,
        contact_name_schema,
        contact_phone_schema,
    )


class SharedContact(BaseModel):
    address: list[contact_address_schema.ContactAddress] | None = None
    avatar: contact_avatar_schema.ContactAvatar | None = None
    email: list[contact_email_schema.ContactEmail] | None = None
    name: contact_name_schema.ContactName | None = None
    organization: str | None = None
    phone: list[contact_phone_schema.ContactPhone] | None = None
