# generated by datamodel-codegen:
#   filename:  send_commands.json

from __future__ import annotations

from pydantic import BaseModel

from .shared.data import AddMembers


class GroupPermissions(BaseModel):
    add_members: AddMembers | None = None
    edit_group: AddMembers | None = None
    send_messages: AddMembers | None = None


class LinkPreviewType(BaseModel):
    base64_thumbnail: str | None = None
    description: str | None = None
    title: str | None = None
    url: str | None = None


class MessageMention(BaseModel):
    author: str | None = None
    length: int | None = None
    start: int | None = None
