# generated by datamodel-codegen:
#   filename:  signal-cli-rest-api.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class AddMembers(Enum):
    only_admins = "only-admins"
    every_member = "every-member"


class EditGroup(Enum):
    only_admins = "only-admins"
    every_member = "every-member"


class SendMessages(Enum):
    only_admins = "only-admins"
    every_member = "every-member"


class GroupPermissions(BaseModel):
    add_members: AddMembers | None = None
    edit_group: EditGroup | None = None
    send_messages: SendMessages | None = None


class LinkPreviewType(BaseModel):
    base64_thumbnail: str | None = None
    description: str | None = None
    title: str | None = None
    url: str | None = None


class MessageMention(BaseModel):
    author: str | None = None
    length: int | None = None
    start: int | None = None
