# generated by datamodel-codegen:
#   filename:  shared.py

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class AddMembers(Enum):
    only_admins = "only-admins"
    every_member = "every-member"


class RemoteDeleteResponse(BaseModel):
    timestamp: str | None = None


class TrustModeRequest(BaseModel):
    trust_mode: str | None = None


class SetPinRequest(BaseModel):
    pin: str | None = None
